version: 0.2

phases:
  install:
    commands:
      # - pip install truffleHog
  pre_build:
    commands: 
      - echo 'git leaks to find and highlight keys - done'
      - docker run zricethezav/gitleaks --repo-url=https://github.com/sadiaashfaq2812/react-buggy -v --leaks-exit-code=0 --depth=100 --report=my-report.json
      
      - echo 'Run dependency check to find vulnerable modules - done' 
      - chmod +x ./dependency-check/bin/dependency-check.sh
      - ./dependency-check/bin/dependency-check.sh --project react-project --scan ./ --out ModuleVulnerabilities
      
      - echho 'Run trufflehog'
      - docker run -v /workspace:/proj dxa4481/trufflehog --regex --entropy=false --max_depth=100 file:///proj
      # - docker run dxa4481/trufflehog --regex --entropy=false https://github.com/sadiaashfaq2812/react-buggy.git
      # - docker run --rm -it --entrypoint='' gruebel/retirejs:latest npm outdated -g
      # - docker run -u zap -p 8080:8080 -p 8090:8090 -i owasp/zap2docker-stable zap-webswing.sh
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      # - Make directiory
      - mkdir test-directory
deploy:
    commands:
    # - Make directiory
    - mkdir code-deploy-directory
artifacts:
  files:
    - '**/*'