steps:
# # Pull docker image of truflehog
# - name: 'sadiaashfaq2812/trufflehog-actions-scan'
#   args: ['pull', 'sadiaashfaq2812/trufflehog-actions-scan']

# Run docker image of trufflehog
- name: 'trufflehog'
  args: ['run', "-v '$(pwd):/proj' sadiaashfaq2812/trufflehog-actions-scan file:///proj > trufflehog_file"]

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/thesisproject1859/react', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/thesisproject1859/react']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'react', '--image', 'gcr.io/thesisproject1859/react', '--port', '3000', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

# - name: 'gcr.io/thesisproject1859/sonar-scanner'
  # args: ['-Dsonar.host.url=https://sonarcloud.io', '-Dsonar.login={specify}', '-Dsonar.projectKey={specify}', '-Dsonar.organization={specify}', '-Dsonar.sources=.']
# tags: ['cloud-builders-community']

# its my cloud build file.