name: CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  check_secrets:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: trufflehog-actions-scan
      uses: SadiaAshfaq2812/react-buggy@master
