name: A workflow for ensuring credentials are not in file
on: 
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]
jobs:
  check_secrets:
    name: Credentials Checker
    runs-on: ubuntu-latest
    steps:        
       - uses: actions/checkout@master
       - name: trufflehog-actions-scan
         uses: SadiaAshfaq2812/trufflehog-actions-scan@master
         with:
          branch: ${{ github.head_ref }}
          # using scanArguments with entropy=true to consider regexes rules for credentials evaluations
          # scanArguments: "--regex --entropy=True --max_depth=20  --rules /regexes.json"
          # using scanArguments with entropy=false to discard regexes rules for credentials evaluations
           scanArguments: "--regex --entropy=False --max_depth=20  --rules /regexes.json"


# # This is a basic workflow to help you get started with Actions
# name: CI

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]

#   pull_request:
#     branches: [ master ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   check_secrets:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     - uses: actions/checkout@master
#     - name: trufflehog-actions-scan
#       uses: https://github.com/SadiaAshfaq2812/react-buggy@master
#       # with:
#       #   scanArguments: "--regex --entropy=False --max_depth=5 --rules /regexes.json" # Add custom options here*
#     - name: Trufflehog Check
#       uses: UnicornGlobal/trufflehog-actions-scan@v1.0.0

#   # dep-check:
#   #   - name: Opinionated OWASP Dependency-Check
#   #     uses: Djelibeybi/opinionated-dependency-check@v1


#     # - uses: actions/checkout@master
#     # - name: trufflehog-actions-scan
#     #   uses: SadiaAshfaq2812/react-buggy@master
#       # with:
#       # scanArguments: "--regex --entropy=False --max_depth=5 --rules /regexes.json"


# #       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
# #       - uses: actions/checkout@v2

# #       # Runs a single command using the runners shell
# #       - name: Run a one-line script
# #         run: echo Hello, world project!

# #       # Runs a set of commands using the runners shell
# #       - name: Run a multi-line script
# #         run: |
# #           echo Add other actions to build,
# #           echo test, and deploy your project.
