name: A workflow for ensuring credentials are not in file
on: 
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]
jobs:
  check_secrets:
    name: Credentials Checker
    runs-on: ubuntu-latest
    steps:        
       - uses: actions/checkout@master
       - name: trufflehog-actions-scan
         uses: sadiaashfaq2812/trufflehog-actions-scan@master
         with:
          branch: ${{ github.head_ref }}
          # using scanArguments with entropy=true to consider regexes rules for credentials evaluations
          # scanArguments: "--regex --entropy=True --max_depth=20  --rules /regexes.json"
          # using scanArguments with entropy=false to discard regexes rules for credentials evaluations
          scanArguments: "--regex --entropy=False --max_depth=20  --rules /regexes.json"